version: "3"
name: ldap_auth

services:
  ldap_auth:
    container_name: server-ldap_auth
    restart: always
    build: .
    image: ldap_auth-server
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py load_all_fixtures &&
      celery -A backend beat --loglevel=INFO &
      celery -A backend worker --loglevel=INFO --concurrency=1 --pool=solo -n workerLDAP &
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Auth_LDAP
    ports:
      - "8000:8000"
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
