"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import password
import os
import ldap
from django_auth_ldap.config import LDAPSearch, LDAPGroupQuery, NestedGroupOfNamesType

# адрес сервера ldap
AUTH_LDAP_SERVER_URI = password.LDAP_HOST

# логин/пароль юзера для коннекта в ldap
AUTH_LDAP_BIND_DN = password.LDAP_HOST_USER
AUTH_LDAP_BIND_PASSWORD = password.LDAP_HOST_USER_PASSWORD

# как будут искатся пользователи в ldap
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    password.LDAP_SEARCH_USER,
    ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"
)

AUTH_LDAP_USER_ATTR_MAP = {
    "username": "sAMAccountName",
    "name": "Name",
    "email": "mail",
    "ldap_id": 'ObjectGUID',
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    password.LDAP_SEARCH_GROUP,
    ldap.SCOPE_SUBTREE,
    "(objectClass=group)"
)

AUTH_LDAP_GROUP_TYPE = NestedGroupOfNamesType()

# AUTH_LDAP_REQUIRE_GROUP = (
#     LDAPGroupQuery(password.LDAP_REQUIRE_GROUP)
#     | LDAPGroupQuery(password.LDAP_GROUP_ADMIN)
# )

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_superuser": password.LDAP_GROUP_ADMIN,
    "is_chief": password.LDAP_GROUP_CHIEF,
    "OGGSK": password.LDAP_OGGSK_GROUP,
    "UO": password.LDAP_OU_GROUP,
    "MATRIX": password.LDAP_MATRIX_GROUP,
}

AUTHENTICATION_BACKENDS = [
    'Auth_LDAP.auth_backend.CustomModelBackend',
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = password.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Auth_LDAP.apps.AuthLdapConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'django_python3_ldap',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': password.db_ip,
        'PORT': password.db_port,
        'NAME': password.db_name,
        'USER': password.db_login,
        'PASSWORD': password.db_password
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Auth_LDAP.CustomUser'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'shared_session_id'
